spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sso
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password: wutong
    port: 6379
server:
  port: 8080
